#include "chunkgeneration.h"
#include "engine/settings.h"

ChunkGeneration &ChunkGeneration::instance() {
  static ChunkGeneration instance;
  return instance;
}

ChunkGeneration::ChunkGeneration() {
  m_generator = FastNoise::NewFromEncodedNodeTree("FQkXCSAJBg@AHpEE@DYmpnZPwwCKQkNAAc@BJC@BEhEHAL/AwAE");

  m_snow = FastNoise::New<FastNoise::Simplex>();
  m_snow->SetScale(400.0f);

  m_seed = Settings::instance().worldSeed();
  m_planetSizeInChunks = Settings::instance().planetSizeInChunks();
}

void ChunkGeneration::generateHeightmap(const ChunkPosition &pos) {
  auto heightMap = std::make_shared<HeightMap>();

  float invWorldSize = 1.0f / (m_planetSizeInChunks * Chunk::SIZE);
  float TAU = 6.28318530718f;
  float scale = m_planetSizeInChunks * Chunk::SIZE / 3.0f; // Adjust this to change the size of terrain
  std::vector<float> xs(Chunk::AREA), ys(Chunk::AREA),
      zs(Chunk::AREA), ws(Chunk::AREA);

  for (int z = 0; z < Chunk::SIZE; ++z) {
    for (int x = 0; x < Chunk::SIZE; ++x) {
      int worldX = pos.x() * Chunk::SIZE + x;
      int worldZ = pos.z() * Chunk::SIZE + z;

      float angleX = worldX * invWorldSize * TAU;
      float angleZ = worldZ * invWorldSize * TAU;

      int i = x + z * Chunk::SIZE;
      xs[i] = std::cos(angleX) * scale;
      ys[i] = std::sin(angleX) * scale;
      zs[i] = std::cos(angleZ) * scale;
      ws[i] = std::sin(angleZ) * scale;
    }
  }

  m_generator->GenPositionArray4D(
      heightMap->heightValues.data(),
      Chunk::AREA,
      xs.data(), ys.data(), zs.data(), ws.data(),
      0.0f, 0.0f, 0.0f, 0.0f,
      m_seed);

  m_snow->GenPositionArray4D(
      heightMap->snowValues.data(),
      Chunk::AREA,
      xs.data(), ys.data(), zs.data(), ws.data(),
      0.0f, 0.0f, 0.0f, 0.0f,
      m_seed + 1);

  std::unique_lock writeLock(m_cacheMutex);
  
  if (m_heightmapCache.contains(pos)) {
    assert(false && "HeightMap for this position was already generated by another thread, this should never happen due to call_once");
  }

  m_heightmapCache.emplace(pos, std::move(heightMap));
}

std::unique_ptr<Chunk> ChunkGeneration::generateChunk(const ChunkPosition &pos) {
  auto chunk = std::make_unique<Chunk>();

  if (pos.y() < 0 || pos.y() >= World::CHUNKHEIGHT) {
    return chunk; // empty chunk
  }

  // Get-or-create the once_flag for this position (map mutation is serialized)
  std::shared_ptr<std::once_flag> flag;
  {
    std::lock_guard lock(m_mapMutex);
    auto [it, _] = m_heightmapGenerationFlags.emplace(
        pos, std::make_shared<std::once_flag>());
    flag = it->second;
  }

  // Only one thread runs generateHeightmap; others wait here
  std::call_once(*flag, &ChunkGeneration::generateHeightmap, this, pos);

  std::shared_ptr<HeightMap> heightMap;
  {
    std::shared_lock readLock(m_cacheMutex);
    heightMap = m_heightmapCache.at(pos); // just copies the shared_ptr, very cheap
  } // lock released here

  for (int z = 0; z < Chunk::SIZE; ++z) {
    for (int x = 0; x < Chunk::SIZE; ++x) {
      int worldX = pos.x() * Chunk::SIZE + x;
      int worldZ = pos.z() * Chunk::SIZE + z;

      int height = heightMap->heightValues[x + z * Chunk::SIZE] * 48 + 96; // Scale and shift noise to get height

      int snowHeight = heightMap->snowValues[x + z * Chunk::SIZE] * 4;

      if (height < 5)
        height = 5; // Ensure there's at least some ground

      for (int y = 0; y <= height - pos.y() * Chunk::SIZE && y < Chunk::SIZE; ++y) {
        if (y + pos.y() * Chunk::SIZE > 137 + snowHeight) {
          chunk->setBlock(x, y, z, Block(4)); // Snow
        } else if (y + pos.y() * Chunk::SIZE > 130 + snowHeight) {
          chunk->setBlock(x, y, z, Block(3)); // Stone
        } else if (y + pos.y() * Chunk::SIZE == height) {
          chunk->setBlock(x, y, z, Block(1)); // Grass
        } else if (y + pos.y() * Chunk::SIZE >= height - 5) {
          chunk->setBlock(x, y, z, Block(2)); // Dirt
        } else {
          chunk->setBlock(x, y, z, Block(3)); // Stone
        }
      }
    }
  }

  return chunk;
}