#include "raytraversal.h"

// Generated by Claude Sonnet 4.6
RayHit RayTraversal::traverse(const Ray &ray, float maxDistance, World *world) {
  // Current block position (integer grid)
  glm::ivec3 blockPos = glm::ivec3(glm::floor(ray.origin));

  // Direction to step in each axis (+1 or -1)
  glm::ivec3 step = glm::ivec3(
      ray.direction.x >= 0 ? 1 : -1,
      ray.direction.y >= 0 ? 1 : -1,
      ray.direction.z >= 0 ? 1 : -1);

  // tMax: distance along ray to the next block boundary on each axis
  // tDelta: distance along ray to cross one full block on each axis
  glm::vec3 tDelta, tMax;

  for (int i = 0; i < 3; i++) {
    if (ray.direction[i] == 0.0f) {
      tDelta[i] = std::numeric_limits<float>::infinity();
      tMax[i] = std::numeric_limits<float>::infinity();
    } else {
      tDelta[i] = std::abs(1.0f / ray.direction[i]);

      // Distance to the first boundary crossing on this axis
      float border = (step[i] > 0)
                         ? (glm::floor(ray.origin[i]) + 1.0f)
                         : glm::floor(ray.origin[i]);

      tMax[i] = std::abs((border - ray.origin[i]) / ray.direction[i]);
    }
  }

  glm::ivec3 prevBlockPos = blockPos;

  while (true) {
    if (world->getBlock(blockPos).isSolid()) {
      RayHit hit;
      hit.hit = true;
      hit.blockPos = blockPos;
      hit.blockBeforePos = prevBlockPos;
      // Compute the actual hit point using the t value of the last step
      float t = std::min({tMax.x, tMax.y, tMax.z});
      hit.hitPoint = ray.origin + ray.direction * (t - std::min(tDelta.x, std::min(tDelta.y, tDelta.z)));
      return hit;
    }

    // Step along the axis with the smallest tMax (closest boundary)
    prevBlockPos = blockPos;

    if (tMax.x < tMax.y && tMax.x < tMax.z) {
      if (tMax.x > maxDistance)
        break;
      blockPos.x += step.x;
      tMax.x += tDelta.x;
    } else if (tMax.y < tMax.z) {
      if (tMax.y > maxDistance)
        break;
      blockPos.y += step.y;
      tMax.y += tDelta.y;
    } else {
      if (tMax.z > maxDistance)
        break;
      blockPos.z += step.z;
      tMax.z += tDelta.z;
    }
  }

  RayHit miss;
  miss.hit = false;
  return miss;
}